<a href="https://colab.research.google.com/github/bedriselimbenek/Statistic/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
from scipy import stats 
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None)  #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=1000)

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print("mean = ", np.mean(samples))
print("median = ", np.median(samples))
print("mode = ", stats.mode(samples))


mean =  99.62192038288332
median =  99.13699327344085
mode =  ModeResult(mode=array([46.45160304]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = print("min = ", np.min(samples))
max = print("max = ", np.max(samples))
q1 =  print("Q1 = ", np.percentile(samples,25))
q3 =  print("Q3 = ", np.percentile(samples,75))
iqr = print("IQR:", (stats.iqr(samples)))

min =  46.451603037265706
max =  147.3553336762112
Q1 =  90.1734938229714
Q3 =  108.77928631185449
IQR: 18.605792488883097


Compute the **variance** and **standard deviation**

In [ ]:
variance = print("variance: ", np.var(samples))
std_dev = print("Std deviation: ", np.std(samples))

variance:  206.69787104468776
Std deviation:  14.37699102888667


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [ ]:
from scipy.stats import kurtosis  # We can use scipy.stats.skew and scipy.stats.kurtosis
from scipy.stats import skew

In [ ]:
skewness = print("skewness: ", skew(samples))
kurtosis = print("kurtosis: ", kurtosis(samples))

skewness:  0.09076386648942865
kurtosis:  0.18058405230398922


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array(np.random.randint(10,20,10))
y

array([17, 10, 19, 13, 15, 15, 13, 13, 15, 15])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)
r

array([[ 1.        , -0.09693668],
       [-0.09693668,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = stats.pearsonr(x, y)

r

(0.758640289091187, 0.010964341301680813)

In [ ]:
from scipy.stats import pearsonr
from scipy.stats import spearmanr

In [ ]:
r = pearsonr(x, y) #Alternative method
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns (plus heatmap)

In [ ]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000